// components/address/location-picker.tsx
"use client";

import { Crosshair } from "@phosphor-icons/react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";

const INITIAL: [number, number] = [-6.2088, 106.8456];

export function LocationPicker() {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<import("leaflet").Map | null>(null);
  const markerRef = useRef<import("leaflet").CircleMarker | null>(null);
  const [point, setPoint] = useState(INITIAL);

  useEffect(() => {
    let cancelled = false;
    async function initialize() {
      if (!containerRef.current || mapRef.current) return;
      const L = await import("leaflet");
      if (cancelled || !containerRef.current) return;
      const map = L.map(containerRef.current).setView(INITIAL, 11);
      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution: "© OpenStreetMap",
        maxZoom: 19,
      }).addTo(map);
      const marker = L.circleMarker(INITIAL, {
        radius: 9,
        color: "#ffffff",
        weight: 3,
        fillColor: "#2563eb",
        fillOpacity: 1,
      }).addTo(map);
      map.on("click", ({ latlng }) => {
        const next: [number, number] = [latlng.lat, latlng.lng];
        marker.setLatLng(next);
        setPoint(next);
      });
      mapRef.current = map;
      markerRef.current = marker;
    }
    initialize();
    return () => {
      cancelled = true;
      mapRef.current?.remove();
      mapRef.current = null;
    };
  }, []);

  function useMyLocation() {
    navigator.geolocation?.getCurrentPosition(({ coords }) => {
      const next: [number, number] = [coords.latitude, coords.longitude];
      setPoint(next);
      markerRef.current?.setLatLng(next);
      mapRef.current?.setView(next, 16);
    });
  }

  return (
    <div>
      <div ref={containerRef} className="h-72 overflow-hidden rounded-2xl border border-slate-200 bg-slate-100" />
      <div className="mt-3 flex flex-wrap items-center justify-between gap-3">
        <p className="text-xs text-slate-500">Klik peta untuk memindahkan pin.</p>
        <Button type="button" variant="secondary" size="sm" onClick={useMyLocation}>
          <Crosshair size={17} /> Gunakan lokasi saya
        </Button>
      </div>
      <input type="hidden" name="latitude" value={point[0]} />
      <input type="hidden" name="longitude" value={point[1]} />
    </div>
  );
}

// app/components/LocationPicker.vue
<script setup lang="ts">
import { PhMapPin as MapPin } from "@phosphor-icons/vue";

const model = defineModel<{ latitude: number; longitude: number }>({ required: true });
const mapEl = ref<HTMLElement>();
const mapReady = ref(false);
let map: import("leaflet").Map | undefined;

onMounted(async () => {
  const L = await import("leaflet");
  if (!mapEl.value) return;

  const latitude = model.value.latitude || -6.2;
  const longitude = model.value.longitude || 106.816666;
  map = L.map(mapEl.value, { zoomControl: true }).setView([latitude, longitude], 13);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution: "&copy; OpenStreetMap contributors",
    maxZoom: 19,
  }).addTo(map);

  const markerIcon = L.divIcon({
    className: "jwlab-map-marker",
    html: '<span class="jwlab-map-marker__pin"><span /></span>',
    iconSize: [42, 48],
    iconAnchor: [21, 46],
  });
  const marker = L.marker([latitude, longitude], { draggable: true, icon: markerIcon }).addTo(map);

  const update = (lat: number, lng: number) => {
    model.value.latitude = lat;
    model.value.longitude = lng;
    marker.setLatLng([lat, lng]);
  };

  map.on("click", (event) => update(event.latlng.lat, event.latlng.lng));
  marker.on("dragend", () => {
    const point = marker.getLatLng();
    update(point.lat, point.lng);
  });
  mapReady.value = true;
  requestAnimationFrame(() => map?.invalidateSize());
});

onBeforeUnmount(() => map?.remove());
</script>

<template>
  <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white" aria-labelledby="location-picker-title">
    <div class="flex items-start gap-3 border-b border-slate-100 p-4 sm:px-5">
      <span class="grid size-10 shrink-0 place-items-center rounded-xl bg-red-50 text-[#ec0016]"><MapPin :size="21" weight="fill" /></span>
      <div>
        <h2 id="location-picker-title" class="text-sm font-black text-slate-900">Tandai lokasi di peta</h2>
        <p class="mt-1 text-xs leading-5 text-slate-500">Klik peta atau geser pin merah tepat ke lokasi penerima.</p>
      </div>
    </div>
    <div class="relative">
      <div ref="mapEl" class="h-72 w-full bg-slate-100 sm:h-80" />
      <div v-if="!mapReady" class="absolute inset-0 grid place-items-center bg-slate-100 text-xs font-bold text-slate-500">Memuat peta...</div>
    </div>
    <div class="flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 px-4 py-3 text-[10px] text-slate-500 sm:px-5">
      <span class="font-bold text-slate-700">Koordinat lokasi</span>
      <span class="font-mono">{{ model.latitude.toFixed(6) }}, {{ model.longitude.toFixed(6) }}</span>
    </div>
  </section>
</template>
