// components/product-card.tsx
import { ArrowRight, CheckCircle } from "@phosphor-icons/react/dist/ssr";
import Image from "next/image";
import Link from "next/link";
import { formatCurrency } from "@/lib/format";
import type { Product } from "@/lib/types";

export function ProductCard({ product }: { product: Product }) {
  const price = product.variant.salePrice ?? product.variant.regularPrice;
  const stock = Math.max(0, product.variant.stockOnHand - product.variant.reservedStock);
  const discount = product.variant.salePrice
    ? Math.round((1 - product.variant.salePrice / product.variant.regularPrice) * 100)
    : 0;

  return (
    <article className="group flex h-full flex-col overflow-hidden border border-black/10 bg-white transition duration-300 hover:-translate-y-1 hover:border-black/25 hover:shadow-[0_22px_60px_rgba(17,18,23,.12)]">
      <Link
        href={`/products/${product.slug}`}
        className="relative block aspect-[4/5] overflow-hidden bg-[#f0f0ec]"
      >
        <Image
          src={product.images[0] || "/product-placeholder.svg"}
          alt={product.name}
          fill
          sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw"
          className="object-contain p-2 transition duration-500 group-hover:scale-[1.055] sm:p-3"
        />
        <div className="absolute left-2.5 top-2.5 flex flex-wrap gap-1.5 sm:left-3 sm:top-3">
          {product.variant.salePrice && (
            <span className="bg-[#e21b2d] px-2 py-1 text-[9px] font-black uppercase tracking-wider text-white shadow-sm sm:text-[10px]">
              -{discount}%
            </span>
          )}
          {stock <= 3 && stock > 0 && (
            <span className="bg-[#111217] px-2 py-1 text-[9px] font-bold text-white sm:text-[10px]">
              Sisa {stock}
            </span>
          )}
        </div>
      </Link>

      <div className="flex flex-1 flex-col border-t border-black/8 p-3.5 sm:p-4">
        <p className="text-[9px] font-black uppercase tracking-[.16em] text-[#1746a2] sm:text-[10px]">
          {product.category.name}
        </p>
        <Link
          href={`/products/${product.slug}`}
          className="mt-2 line-clamp-2 min-h-10 text-sm font-black leading-snug tracking-[-.02em] text-[#111217] group-hover:text-[#e21b2d] sm:min-h-11 sm:text-base"
        >
          {product.name}
        </Link>
        <p className="mt-1 line-clamp-1 text-[10px] font-medium text-slate-400 sm:text-[11px]">
          {product.shortDescription}
        </p>

        <div className="mt-3">
          {product.variant.salePrice && (
            <p className="text-[10px] text-slate-400 line-through sm:text-[11px]">
              {formatCurrency(product.variant.regularPrice)}
            </p>
          )}
          <p className="text-sm font-black text-[#111217] sm:text-base">{formatCurrency(price)}</p>
        </div>

        <div className="mt-3 flex items-center justify-between border-t border-black/8 pt-3 text-[10px] font-semibold text-slate-500 sm:mt-auto sm:text-xs">
          <span className="flex items-center gap-1.5">
            <CheckCircle size={15} weight="fill" className="text-emerald-600" />
            Ready stock
          </span>
          <span className="grid size-7 place-items-center bg-[#111217] text-white transition group-hover:translate-x-0.5 group-hover:bg-[#e21b2d]">
            <ArrowRight size={14} weight="bold" />
          </span>
        </div>
      </div>
    </article>
  );
}

// app/components/ProductCard.vue
<script setup lang="ts">
import { PhArrowUpRight as ArrowUpRight } from "@phosphor-icons/vue";
import { formatCurrency } from "~~/shared/format";
import type { Product } from "~~/shared/types";

const props = defineProps<{ product: Product }>();
const availableStock = computed(() => props.product.variant.stockOnHand - props.product.variant.reservedStock);
const discount = computed(() => {
  const sale = props.product.variant.salePrice;
  if (!sale || sale >= props.product.variant.regularPrice) return 0;
  return Math.round((1 - sale / props.product.variant.regularPrice) * 100);
});
</script>

<template>
  <article class="product-card group flex h-full min-w-0 flex-col overflow-hidden rounded-2xl border border-black/10 bg-white transition duration-300 hover:-translate-y-1 hover:border-black/20 hover:shadow-[0_20px_50px_rgba(7,26,61,.12)]">
    <NuxtLink :to="`/products/${product.slug}`" class="relative block aspect-square overflow-hidden bg-[#f2f3f5]">
      <img :src="product.images[0]" :alt="product.name" class="h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]">
      <span class="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-[#0b4697] shadow-sm backdrop-blur">{{ product.category.name }}</span>
      <span v-if="discount" class="absolute right-3 top-3 rounded-full bg-[#ec0016] px-2.5 py-1 text-[10px] font-black text-white shadow-sm">-{{ discount }}%</span>
      <span class="absolute bottom-3 right-3 grid size-9 translate-y-2 place-items-center rounded-full bg-[#071a3d] text-white opacity-0 shadow-lg transition group-hover:translate-y-0 group-hover:opacity-100"><ArrowUpRight :size="17" weight="bold" /></span>
    </NuxtLink>

    <div class="flex flex-1 flex-col p-4 sm:p-5">
      <NuxtLink :to="`/products/${product.slug}`" class="line-clamp-2 text-base font-black leading-snug text-slate-950 sm:text-lg">{{ product.name }}</NuxtLink>
      <p class="mt-1.5 line-clamp-2 min-h-10 text-xs leading-5 text-slate-500 sm:text-sm">{{ product.shortDescription }}</p>
      <div class="mt-4 flex min-h-11 items-end justify-between gap-2">
        <div class="min-w-0">
          <strong class="block truncate text-base font-black text-slate-950 sm:text-lg">{{ formatCurrency(product.variant.salePrice ?? product.variant.regularPrice) }}</strong>
          <del v-if="product.variant.salePrice" class="block text-[10px] text-slate-400">{{ formatCurrency(product.variant.regularPrice) }}</del>
        </div>
        <span class="shrink-0 text-[10px] font-bold" :class="availableStock > 0 ? 'text-emerald-600' : 'text-red-600'">{{ availableStock > 0 ? `${availableStock} tersedia` : "Habis" }}</span>
      </div>
      <div class="mt-4"><AddToCart :product="product" compact /></div>
    </div>
  </article>
</template>
