// components/site-footer.tsx
import { CheckCircle, QrCode, Truck } from "@phosphor-icons/react/dist/ssr";
import Image from "next/image";
import Link from "next/link";

export function SiteFooter() {
  return (
    <footer className="mt-20 border-t-4 border-[#f7b718] bg-[#062733] text-slate-300">
      <div className="container-shell grid gap-10 py-12 md:grid-cols-[1.4fr_1fr_1fr]">
        <div>
          <div className="flex items-center gap-3">
            <Image
              src="/logo-jwlab-studio.png"
              width={72}
              height={72}
              alt="JWLAB STUDIO"
              className="size-17 object-contain"
            />
            <p className="font-black tracking-[.15em] text-white">JWLAB STUDIO</p>
          </div>
          <p className="mt-4 max-w-sm text-sm leading-6 text-slate-400">
            Action figure 3D print siap koleksi. Setiap pesanan dicek dan dikemas aman.
          </p>
          <div className="mt-5 flex flex-wrap gap-2 text-[11px] font-bold">
            <span className="flex items-center gap-1.5 rounded-lg bg-white/6 px-3 py-2">
              <CheckCircle size={16} className="text-[#f7b718]" /> Produk dicek
            </span>
            <span className="flex items-center gap-1.5 rounded-lg bg-white/6 px-3 py-2">
              <QrCode size={16} className="text-[#f7b718]" /> QRIS
            </span>
            <span className="flex items-center gap-1.5 rounded-lg bg-white/6 px-3 py-2">
              <Truck size={16} className="text-[#f7b718]" /> BCE Express
            </span>
          </div>
        </div>

        <div>
          <p className="footer-title">Belanja</p>
          <div className="mt-4 grid gap-3 text-sm">
            <Link href="/search">Semua produk</Link>
            <Link href="/categories/figure-karakter">Figure karakter</Link>
            <Link href="/categories/chibi-mini-figure">Chibi & mini figure</Link>
            <Link href="/categories/designer-toys">Designer toys</Link>
          </div>
        </div>

        <div>
          <p className="footer-title">Bantuan</p>
          <div className="mt-4 grid gap-3 text-sm">
            <Link href="/account/orders">Pesanan saya</Link>
            <Link href="/account/addresses">Alamat pengiriman</Link>
            <Link href="/cart">Keranjang</Link>
          </div>
        </div>
      </div>

      <div className="border-t border-white/10 py-5 text-center text-xs text-slate-500">
        © {new Date().getFullYear()} JWLAB STUDIO
      </div>
    </footer>
  );
}

// app/components/SiteFooter.vue
<template>
  <footer class="mt-20 bg-[#071a3d] text-slate-300">
    <div class="container-shell grid gap-10 py-14 md:grid-cols-3">
      <div><img src="/logo-jwlab-studio.webp" class="h-24 w-auto" alt="JWLAB STUDIO"><p class="max-w-sm text-sm leading-6">Collectible robot figures and statues crafted for expressive displays.</p></div>
      <div><p class="footer-title">Koleksi</p><div class="mt-4 grid gap-2 text-sm"><NuxtLink to="/search">Semua figure robot</NuxtLink></div></div>
      <div><p class="footer-title">Bantuan</p><div class="mt-4 grid gap-2 text-sm"><NuxtLink to="/account/orders">Pesanan</NuxtLink><NuxtLink to="/account/addresses">Alamat</NuxtLink><span>Pengiriman BCE Express</span></div></div>
    </div>
  </footer>
</template>
