// app/pages/categories/[slug].vue
<script setup lang="ts">
const route = useRoute(); const { data } = await useFetch("/api/catalog");
const category = computed(() => data.value?.categories.find((item) => item.slug === route.params.slug));
const products = computed(() => data.value?.products.filter((product) => product.category.slug === route.params.slug) || []);
if (!category.value) throw createError({ statusCode: 404, statusMessage: "Kategori tidak ditemukan" });
useSeoMeta({ title: () => category.value?.name || "Kategori" });
</script>
<template><section class="container-shell py-12"><p class="eyebrow">Collection</p><h1 class="section-title mt-3">{{ category?.name }}</h1><p class="mt-4 max-w-2xl text-slate-500">{{ category?.description }}</p><div v-if="products.length" class="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><ProductCard v-for="product in products" :key="product.id" :product="product"/></div><div v-else class="surface mt-9 p-10 text-center"><h2 class="text-xl font-black">Koleksi ini masih kosong</h2><p class="mt-2 text-sm text-slate-500">Figure robot untuk kategori ini sedang disiapkan.</p></div></section></template>

// app/categories/[slug]/page.tsx
import { ArrowLeft } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductCard } from "@/components/product-card";
import { getCategories, searchProducts } from "@/lib/catalog";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const category = (await getCategories()).find((item) => item.slug === slug);
  return { title: category?.name ?? "Kategori" };
}

export default async function CategoryPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const category = (await getCategories()).find((item) => item.slug === slug);
  if (!category) notFound();
  const products = await searchProducts("", slug);

  return (
    <section className="container-shell py-8 sm:py-12">
      <Link href="/search" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-[#e84b18]">
        <ArrowLeft size={17} /> Semua koleksi
      </Link>
      <div className="brand-grid mt-7 rounded-3xl bg-[#082f3d] px-6 py-8 text-white sm:px-10 sm:py-11">
        <p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#f7b718]">Kategori koleksi</p>
        <h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-5xl">{category.name}</h1>
        <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{category.description}</p>
      </div>
      <div className="mt-8 grid grid-cols-2 gap-2.5 sm:gap-4 lg:grid-cols-4">
        {products.map((product) => <ProductCard key={product.id} product={product} />)}
      </div>
    </section>
  );
}
